name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u axetrading --password-stdin
        docker build . --tag ghcr.io/axetrading/terraform-test-image:latest
        docker push ghcr.io/axetrading/terraform-test-image:latest
